version: '3.9'

services:
  postgres:
    container_name: postgres
    #image: postgres:13.2
    #image: postgres:14.3
    # command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    build:
      context: postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}

      # volumes:
      #   - "$(pwd)/server.crt:/var/lib/postgresql/server.crt:ro"
      #   - "$(pwd)/server.key:/var/lib/postgresql/server.key:ro" 

    # volumes: 
    #   - ./init:/docker-entrypoint-initdb.d
      # - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      # Would be nice to pass these vars from here, and not the "args" section under.
      # ENV KEYCLOAK_ADMIN: admin
      # ENV KEYCLOAK_ADMIN_PASSWORD: admin

      # DB_VENDOR: postgres
      # DB_ADDR: postgres
      # DB_DATABASE: ${POSTGRESQL_DB}
      # DB_USER: ${POSTGRESQL_USER}
      # DB_PASSWORD: ${POSTGRESQL_PASS}
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin1234
    #image: mykeycloak:latest
    #image: jboss/keycloak:${KEYCLOAK_VERSION}
    build:
      context: keycloak
      dockerfile: Dockerfile
      args:
        MY_KEYCLOAK_ADMIN_PASSWORD: "admin1234"
    ports:
      - "28080:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - local-keycloak
    command:
      - start-dev

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@skobba.net"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - "16543:80"
    depends_on: 
      - postgres
    networks:
      - local-keycloak

  debianssh:
    container_name: debianssh
    build:
      context: debianssh
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
      - "8000:80"
    depends_on: 
      - postgres
    networks:
      - local-keycloak

networks:
  local-keycloak: